name: CI
on: [push, pull_request]

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/env

      - name: Test
        run: cat ./aftman.toml

      - name: Run setup-aftman
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/env

      - name: Run setup-aftman
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/env

      - name: Run setup-aftman
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

