name: CI
on: [push, pull_request]

jobs:
  test_linux_no_trust:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/env
        with:
          no-trust-check: true

  test_mac_no_trust:
    runs-on: macos-latest
    steps:
      - uses: ./.github/actions/env
        with:
          no-trust-check: true

  test_windows_no_trust:
    runs-on: windows-latest
    steps:
      - uses: ./.github/actions/env
        with:
          no-trust-check: true

  test_linux_with_trust:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/env
        with:
          trusts: "Kampfkarren/selene JohnnyMorganz/stylua rojo-rbx/rojo"

  test_mac_with_trust:
    runs-on: macos-latest
    steps:
      - uses: ./.github/actions/env
        with:
          trusts: "Kampfkarren/selene JohnnyMorganz/stylua rojo-rbx/rojo"

  test_windows_with_trust:
    runs-on: windows-latest
    steps:
      - uses: ./.github/actions/env
        with:
          trusts: "Kampfkarren/selene JohnnyMorganz/stylua rojo-rbx/rojo"

  test_linux_version_and_path:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/env
        run: "mkdir project"
        with:
          version: 0.2.2
          path: "./project"

  test_mac_version_and_path:
    runs-on: macos-latest
    steps:
      - uses: ./.github/actions/env
        run: "mkdir project"
        with:
          version: 0.2.2
          path: "./project"


  test_windows_version_and_path:
    runs-on: windows-latest
    steps:
      - uses: ./.github/actions/env
        run: "mkdir project"
        with:
          version: 0.2.2
          path: "./project"
